# (PART) Price Index Theory{-}

# Syllabus for Price Index Theory

Why are certain index-number formulas used to compute a price index? Answering this question requires a theory of price indices that can be used to evaluate the properties of a price index, and determine if one index number is better than another.

The goal of this module is to provide the theoretical underpinnings of a price index, with a particular focus on motivating the index-number formulas that are used in practice. By the end of the module, an individual should:

1. Be familiar with the three theoretical approaches to develop a price index.

2. Know how the three approaches can be used to motivate commonly-used index numbers.

This module is useful for both users and compilers of price indices with a basic understanding of how to construct a price index, and who would like to get a deeper understanding of why particular index-number formulas are used.

This module consists of self-directed readings, along with an assignment. In total, about 10 to 15 hours should be devoted for this module.

Prerequisites: Introduction to Price Indices, at least one intermediate micro-theory course, and at least an introductory course in probability and statistics. An advanced micro-theory course is helpful.

Evaluation for this module is based on an assignment consisting of 20 multiple-choice/true-false questions that draw on material in the course content and readings. Collaboration on the assignment is welcomed, but each person must submit their own unique work. Passing this module requires at least a 65% on the assignment.

Readings for this module come from chapters 15--18 of the PPI manual [@ppimanual] and/or the CPI manual [@cpimanual], published by the IMF ([freely available on their website](https://www.imf.org/en/Publications/Manuals-Guides/Issues/2016/12/30/Producer-Price-Index-Manual-Theory-and-Practice-16966)), as well as the review of price-index theory by @balk1995.

Please email one of the course instructors (either [Steve Martin](mailto:steve.martin5@canada.ca) or [Rebecca Meier](mailto:rebecca.meier@canada.ca)) if you have any questions, or need help with any of the course material or assignment.

# What is price-index theory?

There are three broad approaches for motivating the price-index formulas that get used in practice by statistical agencies---the axiomatic approach, the economic approach, and the stochastic approach. Each approach is useful in its own right, and all three give different perspectives and understandings for the various index-number formulas that are used to construct price indices. Taken together, these different approaches constitute a theory of price indices.

Each of the three approaches can be thought of as answering a different question about how to construct a price index. The axiomatic approach attempts to answer the question "How can information for a collection of prices and quantities be combined to satisfy certain properties?" This is essentially a set theoretic approach for how to best construct an index number. By contrast, the economic approach attempts to answer the question "What should a price index measure?" The goal with the economic approach is to use the machinery of microeconomic theory to define a price index so as to measure the experience of a change in prices for consumers and producers. The stochastic approach is more pragmatic in its scope, and attempts to answer the question "How can information on prices be used to best predict a change in price for a good or service?" This is essentially a question about how to best inflate and deflate prices over time.

This part of the course gives a practical introduction to each of the three approaches, focusing on how they can be used to motivate the way price indices are constructed in practice. Despite having a more practical focus, however, this material is still concerned with theory that can be quite technical. Rather than focusing on the technical details (of which there are many), this part of the course gives enough of a glimpse into the technical machinery to show what is going on, while providing the economic intuition and overarching ideas from the theory.

# The axiomatic approach

A price index combines information about prices and quantities at two points in time in order to produce a ratio of prices between these points in time. Unless there is only one price at each point in time, however, there is no unique way to combine prices over time---there are an infinity of possible index-number formulas that can be used to calculate a price index. This embarrassment of riches is undesirable, as it introduces considerable choice into how a price change should be measured. The axiomatic approach attempts to solve this problem by considering a general class of price indices, and finding which members of this class satisfy certain intuitive, or reasonable, properties that a price index ought to satisfy. This is equivalent to making a normative statement about how a price index should behave---what are the fundamental axioms that define a price index? The idea is to start with a very broad class of possible index-number formulas, and define axioms to whittle away index-number formulas that don't behave as a price index should.

The ideal outcome from the axiomatic approach is a single, unique index-number formula that satisfies a minimal set of uncontroversial conditions that a price index ought satisfy. This would mean that there is only one index-number formula that should be used to make a price index. The reality, however, is that compromises must be made, and keeping certain conditions requires ignoring others. Consequently, a distinction is made between axioms---fundamental statements that any reasonable price index should satisfy---and tests, which are properties that are desirable but not as fundamental as axioms. A small set of key axioms are always maintained, whereas tests can be mutually inconsistent, and choices need to be made about which tests an index should satisfy depending on its purpose. Axioms can be seen as the first sieve to remove any unreasonable index-number formulas, with tests acting as a second sieve to further refine what is left over.

This section of the course starts the journey into price index theory by giving a brief outline of the axiomatic approach to price index theory. This has been an area of considerable study, and consequently there is a lot of interesting material that is not covered in this course. The interested reader can consult either @cpimanual[Chapter 16] or @ppimanual[Chapter 16] for more detail, or @balk2008.

&#128214; @balk1995, skip section 4 and appendix.

&#128214; PPI Manual: Chapter 1, section C.

## An abstract price index

In its abstract form, a price index is a function $I$ that takes four arguments---period-0 prices $p_{0}$, period-$t$ prices $p_{t}$, period-0 quantities $q_{0}$, and period-$t$ quantities $q_{t}$, for $n$ distinct goods and services---and returns a single value. It is a rule that turns information on prices and quantities at two points in time into one number that summarizes the change in prices. To simplify notation, prices and quantities here are vectors of prices and quantities at a point in time; for example, with $n$ distinct goods and services, prices in period 0 are given by $p_0 = (p_{10}, p_{20}, \ldots, p_{n0})$. This notation is useful, as a price index is a way to distill information for many prices and quantities into a single value; for example, with 25 goods and services, the price index takes 100 pieces for information (50 prices and 50 quantities) and turns it into one piece of information. For a particular collection of prices and quantities, the index value is given by $I(p_{t}, p_{0}, q_{t}, q_{0})$.

Most price indices can be expressed in this abstract form. For example, a Laspeyres index is simply
\begin{align*}
I(p_{t}, p_{0}, q_{t}, q_{0}) = \frac{\sum_{i=1}^{n} p_{it}q_{i0}}{\sum_{i=1}^{n} p_{i0}q_{i0}}.
\end{align*}
Index-number formulas that don't make use of quantity information require no special treatment---the index value is just independent of whatever quantities were sold. For example, the Jevons index is 
\begin{align*}
I(p_{t}, p_{0}, q_{t}, q_{0}) = \prod_{i=1}^{n} \left(\frac{p_{it}}{p_{i0}}\right)^{1 / n}.
\end{align*}

While most index-number formulas fit in this abstract representation, price indices that use information in a period other than period 0 or period $t$, such as a Lowe or Young index, do not. This is an important point, as the axiomatic approach implicitly ignores these types of price indices from the start, rather than using axioms to evaluate their reasonableness as a price index.

## The axioms

There are five key axioms that any price index should satisfy for all collections of prices and quantities. These axioms can be seen as generalizing the properties of the ratio of prices between period $t$ and period 0 for a single good or service to settings with many goods and services.

1. **Monotonicity** $I(p'_{t}, p_{0}, q_{t}, q_{0}) > I(p_{t}, p_{0}, q_{t}, q_{0})$ if $p'_{t} \geq p_{t}$ and $p'_{t} \neq p_{t}$, and $I(p_{t}, p'_{0}, q_{t}, q_{0}) < I(p_{t}, p_{0}, q_{t}, q_{0})$ if $p'_{0} \geq p_{0}$ and $p'_{0} \neq p_{0}$.

2. **Linear homogeneity** $I(cp_{t}, p_{0}, q_{t}, q_{0}) = cI(p_{t}, p_{0}, q_{t}, q_{0})$ for any $c > 0$.

3. **Identity** $I(p_{0}, p_{0}, q_{t}, q_{0}) = 1$.

4. **Homogeneity of degree zero** $I(cp_{t}, cp_{0}, q_{t}, q_{0}) = I(p_{t}, p_{0}, q_{t}, q_{0})$ for any $c > 0$.

5. **Dimensional invariance** If $A$ is a diagonal matrix of positive numbers, then $I(Ap_{t}, Ap_{0}, A^{-1}q_{t}, A^{-1}q_{0}) = I(p_{t}, p_{0}, q_{t}, q_{0})$.

All of these axioms are fairly straightforward to understand from their mathematical representation, perhaps with the exception of dimensional invariance, and are quite intuitive. Monotonicity simply means that a price index is increasing in period $t$ prices and decreasing in period 0 prices---larger period $t$ prices produce larger index values and larger period 0 prices produce smaller index values. This seems like a necessary condition for a price index to meaningfully measure inflation, as an index that does not satisfy monotonicity can decrease when prices increase.

Linear homogeneity is probably the least intuitive of the axioms, and says that multiplying all period $t$ prices by a constant is the same as multiplying the entire index by a constant, so that a proportional increase in prices results in a proportional increase in the index. To see why this makes sense, consider two cities (A and B) that have all the same prices in period 0. If all prices in city A increase by twice as much as prices in city B between period 0 and period $t$, with quantities purchased remaining the same in the two cities (because relative prices are the same in both cities), then it is reasonable to say that prices in city A have increased by twice as much as in city B.

The identity axiom is simple, and states that a price index does not show a change in prices if prices do not change. Like the monotonicity axiom, this seems like a necessary requirement for a price index to measure inflation; otherwise, a price index could show a change in prices when prices do not change over time.

Homogeneity of degree zero means that multiplying all prices by a constant has no impact on an index---the currency that prices are measured in does not affect the value of a price index. An index-number formula that does not satisfy homogeneity of degree zero can give a different measure of inflation depending on the currency prices are measured in, and cannot be used to compare inflation in different countries.

Dimensional invariance looks complex, but it simply says that changing the units of measurement does not change the index value. A price index should not change if all prices are multiplied by a constant and all quantities are divided by the same constant---a price index should not depend on the units of measurement.

As an example, it is straightforward to see that the Laspeyres index satisfies all five axioms.

1. For monotonicity, 
    \begin{align*}
I(p'_{t}, p_{0}, q_{t}, q_{0}) =  \frac{\sum_{i=1}^{n} p'_{it}q_{i0}}{\sum_{i=1}^{n} p_{i0}q_{i0}} > \frac{\sum_{i=1}^{n} p_{it}q_{i0}}{\sum_{i=1}^{n} p_{i0}q_{i0}} = I(p_{t}, p_{0}, q_{t}, q_{0}) 
    \end{align*}
    whenever each $p'_{it} \geq p_{it}$, with at least one strictly greater. The opposite holds if each $p'_{i0} \geq p_{i0}$, with at least one strictly greater.

2. For linear homogeneity,
    \begin{align*}
I(cp_{t}, p_{0}, q_{t}, q_{0}) =  \frac{\sum_{i=1}^{n} cp_{it}q_{i0}}{\sum_{i=1}^{n} p_{i0}q_{i0}} = \frac{c\sum_{i=1}^{n} p_{it}q_{i0}}{\sum_{i=1}^{n} p_{i0}q_{i0}} = cI(p_{t}, p_{0}, q_{t}, q_{0}) 
    \end{align*}
    for any $c > 0$.

3. For identity, 
    \begin{align*}
I(p_{0}, p_{0}, q_{t}, q_{0}) =  \frac{\sum_{i=1}^{n} p_{i0}q_{i0}}{\sum_{i=1}^{n} p_{i0}q_{i0}} = 1.
    \end{align*}

4. For homogeneity of degree zero,
    \begin{align*}
I(cp_{t}, cp_{0}, q_{t}, q_{0}) =  \frac{\sum_{i=1}^{n} cp_{it}q_{i0}}{\sum_{i=1}^{n} cp_{i0}q_{i0}} = \frac{c\sum_{i=1}^{n} p_{it}q_{i0}}{c\sum_{i=1}^{n} p_{i0}q_{i0}} = I(p_{t}, p_{0}, q_{t}, q_{0}) 
    \end{align*}
    for any $c > 0$.

5. For dimensional invariance, if
    \begin{align*}
A = 
\begin{bmatrix}
a_1 & \ldots & 0 \\
\vdots & \ddots & \vdots \\
0 & \ldots & a_n
\end{bmatrix}
    \end{align*}
    then 
    \begin{align*}
I(Ap_{t}, Ap_{0}, A^{-1}q_{t}, A^{-1}q_{0}) = \frac{\sum_{i=1}^{n} a_{i}p_{it}a_{i}^{-1}q_{i0}}{\sum_{i=1}^{n} a_{i}p_{i0}a_{i}^{-1}q_{i0}} = \frac{\sum_{i=1}^{n} p_{it}q_{i0}}{\sum_{i=1}^{n} p_{i0}q_{i0}} = I(p_{t}, p_{0}, q_{t}, q_{0}). 
    \end{align*}

It should be fairly safe to say that any sensible price index should satisfy these axioms. Although there are many price indices that do, the axioms work to exclude unreasonable index-number formulas that make no sense for measuring changes in prices.

## Counter examples

For the most part, it is difficult to write down a half-way decent price that does not satisfy the five axioms in the previous section. Pathological examples abound, but it is more interesting to look at reasonable cases where an index-number formula does not satisfy all the axioms.^[Two interesting pathological cases have to do with failure of monotonicity for the geometric Laspeyres and Paasche indices. Although the geometric Laspeyres is always increasing in period-$t$ prices, it can also increase in period-0 prices. Necessary for this is that $p_{i1} / p_{i0} \geq \exp(1) I(p_{1}, p_{0}, q_{t}, q_{0}) \approx 2.72 I(p_{1}, p_{0}, q_{t}, q_{0})$ for at least one good $i$, so that at least some goods experience a change in price that is considerably larger than the change in price for the other goods. Similarly, while the geometric Paasche is always decreasing in period-0 prices, it can also decrease in period-$t$ prices. Necessary for this to be the case is that $p_{i1} / p_{i0} \leq I(p_{1}, p_{0}, q_{t}, q_{0}) / \exp(1) \approx I(p_{1}, p_{0}, q_{t}, q_{0}) / 2.72$ for at least one good $i$. See @balk2008[Section 3.12].] Two interesting examples of reasonable price indices that do not satisfy the five axioms are the Dutot index and the median-value index (i.e., the index that takes the median price relative). 

The Dutot index satisfies all axioms except dimensional invariance, whereas the mean-value index satisfies all axioms except monotonicity. To see why the Dutot index does not satisfy dimensional invariance, suppose there are only two goods (i.e., $n = 2$) with $p_{1t} = 1$, $p_{2t} = 2$, and $p_{10} = p_{20} = 1$, and with 
\begin{align*}
A = 
\begin{bmatrix}
1 & 0 \\
0 & 2
\end{bmatrix}.
\end{align*}
In this case
\begin{align*}
I(Ap_{t}, Ap_{0}, A^{-1}q_{t}, A^{-1}q_{0}) = \frac{1 \times 1 + 2 \times 2}{1 \times 1 + 2 \times 1} = 5 / 3
\end{align*}
and 
\begin{align*}
I(p_{t}, p_{0}, q_{t}, q_{0}) = \frac{1 + 2}{1 + 1} = 3 / 2 \neq I(Ap_{t}, Ap_{0}, A^{-1}q_{t}, A^{-1}q_{0}),
\end{align*}
thus failing the dimensional invariance axiom. This simply formalizes the well known issue with the Dutot index that all goods and services must be measured in the same units for it to be useful.

To see that the median price index does not satisfy monotonicity, suppose there are 3 goods such that $p_{1t} = 1$, $p_{2t} = 2$, $p_{3t} = 3$, and $p_{10} = p_{20} = p_{30} = 1$. The median index returns the value 2 (the median price relative). Now if $p'_{1t} = 1$, $p'_{2t} = 2$, and $p'_{3t} = 4$, the median index still returns 2; prices have increased, but the index value remains the same.

## The tests

In addition to the five axioms, there are three important tests that may be desirable for a price index to satisfy. These tests are nice-to-have properties of an index, but are not as fundamental as the axioms. They act as a way to further narrow the set of price indices that satisfy the five axioms.

Stating these tests requires the concept of a quantity index, a function $Q$ that is identical to a price index except that the role of prices and quantities is reversed. A quantity index maps quantities and prices to produce a number, although instead of giving the change in price over time, a quantity index gives the change in physical quantities over time. A quantity index should also satisfy the five axioms (switching prices with quantities).

With a quantity index in hand, the three key tests are as follows.

1. **Circularity test** $I(p_{t}, p_{0}, q_{t}, q_{0}) = I(p_{k}, p_{0}, q_{k}, q_{0}) I(p_{t}, p_{k}, q_{t}, q_{k})$.

2. **Product test** $I(p_{t}, p_{0}, q_{t}, q_{0}) Q(q_{t}, q_{0}, p_{t}, p_{0}) = \frac{\sum_{i = 1}^{n} p_{it}q_{it}}{\sum_{i = 1}^{n} p_{i0}q_{i0}}$. 

3. **Consistency in aggregation** For any partition of $n$ goods into $k = 1, \ldots, m$ distinct groups, there is a function $\psi$ such that $\psi(I(p_{t}, p_{0}, q_{t}, q_{0}), V_{0}, V_{t}) = \sum_{k = 1}^{m} \psi(I(p_{kt}, p_{k0}, q_{kt}, q_{k0}), V_{k0}, V_{kt})$, where $V_{kt} = \sum_{i = 1}^{n_{k}} p_{ikt}q_{ikt}$ is the value of the $n_{k}$ goods for group $k$ in period $t$, with $V_{t} = \sum_{k = 1}^{m} V_{kt}$ being the total value in period $t$, and if $I(p_{kt}, p_{k0}, q_{kt}, q_{k0}) = c$ for all $m$ groups, then $I(p_{t}, p_{0}, q_{t}, q_{0}) = c$.

The circularity test is straightforward, and expresses the idea that an index between two periods can be calculated by chaining the index for consecutive periods together. The circularity test legitimizes the use of chaining when calculating an index, and using period-over-period changes in price to calculate an index with a fixed base period. It also legitimizes rebasing an index.

The product test is similarly straightforward, and says that the change in aggregate value between two periods can be decomposed into a price index and a quantity index. The product tests legitimizes the use of price indices for deflating aggregate values in a national accounting framework.

The consistency in aggregation test looks complicated, but expresses a simple idea: a price index should be an aggregate of sub-indices, where aggregation depends on only the index itself and the total value of the goods for each sub-index. Consistency in aggregation legitimizes the hierarchical calculation of a price index, where price indices are calculated for increasingly broad categories of goods using the same index-number formula throughout, with value shares as weights.

As an example, the Laspeyres index satisfies the product test and the consistency in aggregation test.^[The Laspeyres index does not satisfy the circularity test, as a Laspeyres index would need to be multiplied with a Lowe index to return a Laspeyres index.] For the product test, let the quantity index be
\begin{align*}
Q(q_{t}, q_{0}, p_{t}, p_{0}) = \frac{\sum_{i = 1}^{n} p_{it}q_{it}}{\sum_{i = 1}^{n} p_{it}q_{i0}},
\end{align*}
(this is the Paasche quantity index) so that
\begin{align*}
I(p_{t}, p_{0}, q_{t}, q_{0}) Q(q_{t}, q_{0}, p_{t}, p_{0}) &= \frac{\sum_{i = 1}^{n} p_{it}q_{i0}}{\sum_{i = 1}^{n} p_{i0}q_{i0}} \frac{\sum_{i = 1}^{n} p_{it}q_{it}}{\sum_{i = 1}^{n} p_{it}q_{i0}} \\
&= \frac{\sum_{i = 1}^{n} p_{it}q_{it}}{\sum_{i = 1}^{n} p_{it}q_{i0}}.
\end{align*}

For the consistency in aggregation test, let $\psi(I(p_{t}, p_{0}, q_{t}, q_{0}), V_{0}, V_{t}) = V_0 I(p_{t}, p_{0}, q_{t}, q_{0})$, so that the test becomes
\begin{align*}
I(p_{t}, p_{0}, q_{t}, q_{0}) = \sum_{k = 1}^{m} \frac{V_{k0}}{V_0} I(p_{kt}, p_{k0}, q_{kt}, q_{k0}).
\end{align*}
The Laspeyres index obviously satisfies this condition as $V_{k0} / V_0$ is the period-0 expenditure/revenue share for the products in group $k$.

## An impossibility result

Ideally there would be a single price index that satisfies the five axioms and three tests of the previous sections. This would mean that there is only one index-number formula that should ever be used, at least for the purposes of creating national statistics. However, it can be shown that there is no price index that satisfies the identity axiom, the circularity test, and the product test [@balk1995, Theorem 1], and so *a fortiori* there is no index that satisfies all five axioms and all three tests. This is because there is a trade-off between having an index that can be chained across successive periods (circularity test), and an index that fits in a national accounting framework (product test). Thus, the usefulness of a particular test depends on the use of the index, and this matters for selecting a best index in the axiomatic framework.

## Motivating the Jevons and Laspeyres indices

Although there is no index that satisfies all five axioms and all three tests, the five axioms, along with the circularity test, uniquely define a price index as being a geometric price index with weights that do not change over time [@balk1995, Theorem 11 and Remark 11.1]. That is, a price index satisfies the five axioms and the circularity test if and only if
\begin{align*}
I(p_{t}, p_{0}, q_{t}, q_{0}) = \prod_{i = 1}^{n} \left(\frac{p_{it}}{p_{i0}}\right)^{\omega_{i}},
\end{align*}
where $\sum_{i = 1}^{n} \omega_{i} = 1$. Note that constancy of the weights over time rules out the Törnqvist index.

Switching out the circularity test for the product test, the arithmetic Laspeyres and Paasche indices are the only indices that satisfy the five axioms, the product test, and the consistency in aggregation test [@balk1995, Corollary 16]. That is, the price index must either be
\begin{align*}
I(p_{t}, p_{0}, q_{t}, q_{0}) = \frac{\sum_{i = 1}^{n} p_{it}q_{i0}}{\sum_{i = 1}^{n} p_{i0}q_{i0}}
\end{align*}
or
\begin{align*}
I(p_{t}, p_{0}, q_{t}, q_{0}) = \frac{\sum_{i = 1}^{n} p_{it}q_{it}}{\sum_{i = 1}^{n} p_{i0}q_{it}}.
\end{align*}

These stark results help to motivate the use of these simple indices, and give some practical guidance for when to use them. A geometric index is useful when chaining an index is relatively more important than deflating aggregate values, whereas an arithmetic Laspeyres (or Paasche) index is useful when deflating aggregate values in a national accounting framework is relatively more important than using a chained calculation. This helps to explain why price indices produced by statistical agencies tend to use a geometric index for calculating elemental indices, and an arithmetic index for calculating higher-level indices. At the lowest level in an index's hierarchy, it is important to be able to calculate the elemental indices using period-over-period changes in price, but these indices don't tend to be used for deflating aggregate values. At higher levels of aggregation, there is a need to be able to deflate aggregate values, but no need for chaining period-over-period changes in price to calculate the index, as it is aggregated up from the elemental indices.

It is worth remarking that the Fisher index usually comes out as the theoretical ideal in an axiomatic framework.^[Or sometimes the Törnqvist or Walsh indices, depending on the particular axioms---see @balk2001 and @balk2008[Sections 3.6.4 and 3.6.5.].] This occurs because the product test is maintained without requiring consistency in aggregation, as well as imposing some other tests. Consequently, the Fisher index may be more appropriate if a price index is not calculated using a hierarchical structure. But it is important to note that this is not a foregone conclusion---one of the key results from the axiomatic approach is the ideal price index depends on its purpose, and there do not exist any universally applicable price indices.

# The economic approach

The axiomatic approach to constructing a price index revolves around finding a way to combine information on prices and quantities in order to satisfy certain conditions. The focus is essentially set theoretic, and the goal is to define a relationship between prices over time that has the properties a price index ought to have. Except for perhaps the product test, there is no economic content to the axiomatic approach---it is a purely mathematical exercise. The economic approach, by contrast, seeks to examine the underlying economic phenomenon that a price index should measure, using the microeconomic theory of a representative, competitive firm (for a producer price index) or a representative consumer (for a consumer price index). Exactly how price information should be combined to measure a change in prices over time is completely determined by the economic concept to be measured.

Although the economic approach offers a parsimonious way to construct a price index, the validity of this approach relies on making strong assumptions about firm/consumer behavior and market conditions. The most important---and perhaps strongest---assumption is that there is a single, representative firm or consumer in the market with no market power (i.e., takes market prices as given). Having a representative firm is not a restrictive assumption if the market is competitive, but competitive behavior is indispensable [@ppimanual, Chapter 18].^[The firm is also assumed to make choices to maximize profitability. Although not a controversial assumption, this need not be the only motivation for the firm---see @martin2019.] This is problematic as most markets are characterized by some degree of imperfect competition, causing the theory to fall apart. Conversely, having a consumer take prices as given is a standard assumption, but having a representative consumer is difficult to justify, and cannot be easily relaxed [@pollak1980; @kirman1992].^[The representative consumer is assumed to choose consumption to maximize utility. Although a standard assumption, it is becoming less accepted over time as behavioral considerations are becoming part of microeconomic theory.] Consequently, the economic approach is best seen as a consistent way to conceptualize a price index, rather than a recipe for finding an economically-superior price index, and is the least applicable of the three approaches.

This section of the course gives a brief introduction to the economic approach. As with the axiomatic approach, the focus is on motivating index-number formulas used in practice, and there is a good deal of interesting material that is not covered. Unlike the axiomatic approach, different types of indices require separate analysis because they're measuring different economic phenomena.

&#128214; PPI Manual: Chapter 1, section E; Chapter 17, paragraphs 17.1--17.26 and 17.61--17.67.

&#128214; CPI Manual: Chapter 1, paragraphs 1.85--1.107.

## Input-price index

The goal of an input-price index is to measure the change in the cost of a representative firm’s intermediate inputs, holding outputs fixed at some reference level. This is analogous to a fixed-basket index, except now the economic conditions facing the firm are held fixed, rather than the quantity of inputs used. This distinction is practically important, and means that there are no limits on the firm’s ability to substitute more expensive inputs for less expensive inputs when prices change. An input-price index can alternatively be thought of as a cost-of-production index, analogous to a cost-of-living index for a consumer price index---an input-price index measures the firm’s experience of a change in input prices.

To fix notation, let $y$ be the amount of output a firm produces, $q$ be the quantity of inputs available, and $p$ the price of primary inputs. As with the axiomatic approach, these are vectors of values (i.e., $y$ is a vector with the quantity of each output the firm produces). Taking $y$ as fixed, and assuming the firm has no market power in the inputs market (so that the firm treats $p$ as fixed), a profit-maximizing firm will choose its inputs, $q$, to minimize the cost of achieving outputs $y$. The result of this exercise is the firm’s expenditure function, $e(p, y)$, that gives the minimum cost for purchasing the inputs required to produce $y$ units of output.^[Formally, $e(p, y) = \min_{q \in V(y)} p \cdot q$, where $V(y)$ is the set of inputs that produce at least $y$ units of output. This function is well-defined under fairly mild regularity conditions on the set $V(y)$ (namely that is it non-empty and closed)---see @mcfadden1978.] Because the firm is a profit-maximizer, this minimum cost of product will agree with their actual cost of production under different configurations of prices for inputs and outputs produced.

Having defined the firm’s expenditure function, it is then simple to define an input cost index between period 0 and period $t$ as
\begin{align*}
I^{C} = \frac{e(p_{t}, y_{0})}{e(p_{0}, y_{0})},
\end{align*}
where $y_{0}$ is the amount of output produced by the firm in period 0. The input-price index measures a change in input prices by comparing the expenditure required to satisfy a fixed set of economic (output) conditions over time.

There is actually an entire family of input-price indices depending on the level at which quantities are fixed in the expenditure function. The input-price index defined above is a Laspeyres-like input-price index because the economic conditions facing the firm are fixed at their period 0 values; a Paasche-like index fixes output at its period-$t$ level. However, the intuition is the same in all cases, so attention is restricted to the Laspeyres-like input-price index above to keep the presentation simple.

It is helpful to understand how the input-price index differs from a Laspeyres index in order to appreciate the economic approach to constructing a price index. It is easy to see that
\begin{align*}
e(p_{0}, y_{0}) = \sum_{i = 1}^{n} p_{i0} q_{i0};
\end{align*}
the value of the period-0 expenditure function is simply the observable expenditure on inputs in period 0, for otherwise the firm couldn't be operating to maximize profit in period 0. Now, in period $t$,
\begin{align*}
e(p_{t}, y_{0}) \leq \sum_{i = 1}^{n} p_{it} q_{i0}.
\end{align*}

Obviously the inputs used in period 0 are good enough to produce the amount of output in period 0, but this choice of inputs need not minimize the cost of production at period-$t$ prices. If the price of an input increases between period 0 and period $t$, the firm will usually substitute away from that input and use more of a relatively cheaper input in order to minimize cost while still producing $y_{0}$ units of output. This substitution is not reflected in the choice of inputs $q_{0}$, and so this bundle of inputs will cost more than the cost-minimizing bundle of inputs that can produce $y_{0}$ units of output at period-$t$ prices.

These two expression can now be used to show that 
\begin{align*}
\frac{e(p_{t}, y_{0})}{e(p_{0}, y_{0})} = \frac{e(p_{t}, y_{0})}{\sum_{i = 1}^{n} p_{i0} q_{i0}} \leq \frac{\sum_{i = 1}^{n} p_{it} q_{i0}}{\sum_{i = 1}^{n} p_{i0} q_{i0}}.
\end{align*}
The Laspeyres index thus overstates the price movement between period 0 and period $t$ because it does not take into account the substitution of inputs from a change in price that features as part of the input-price index---there is a positive substitution bias. This is the key insight from the economic approach---there is a divergence between standard index-number formulas used to measure a change in price and the economic change in price---and is the impetus to derive index-number formulas that can be used to calculate the economic input-price index.

## Output-price index

An output-price index is analogous to an input-price index; the only difference is that the index compares the value of output over time, rather than the cost of inputs, holding economic conditions fixed. To this end, an output-price index compares the maximum revenue a representative firm could receive at two points in time, given a fixed set inputs for production.

Modifying the notation of the previous section, let $p$ be the price of outputs $y$, rather than the price of inputs $q$. Taking inputs fixed at $q$, a profit maximizing firm chooses its outputs $y$ to maximize revenue, given prices $p$. This results in the firm’s revenue function, $r(p, q)$, that gives the maximum revenue the firm could earn given market prices and a fixed quantity of inputs.^[Formally, $r(p, q) = \max_{y \in Y(q)} p \cdot y$, where $Y(q)$ is the set of outputs that produce with at most $q$ units of input. This function is well-defined under fairly mild regularity conditions on the set $Y(q)$ (namely that is it compact)---see @mcfadden1978.] As with an input-price index, the output-price index is defined as
\begin{align*}
I^{R} = \frac{r(p_{t}, q_{0})}{r(p_{0}, q_{0})}.
\end{align*}
An output-price index measures the value of a firm’s output over time, given a fixed amount of inputs.

In contrast to an input-price index, an output-price index is always larger than a Laspeyres index. In period 0, the revenue for a firm is simply
\begin{align*}
r(p_{0}, q_{0}) = \sum_{i = 1}^{n} p_{i0} y_{i0};
\end{align*}
the value of the period-0 revenue function is simply the observable revenue period 0, for otherwise the firm couldn't be operating to maximize profit in period 0. Now, in period $t$,
\begin{align*}
r(p_{t}, q_{0}) \geq \sum_{i = 1}^{n} p_{it} y_{i0}
\end{align*}
as the firm will produce relatively more of the outputs that have increased in price, while using the same amount of inputs. The firm substitutes away from less profitable outputs, something not reflected in the firm’s choice of period-0 production. Consequently,
\begin{align*}
\frac{r(p_{t}, q_{0})}{r(p_{0}, q_{0})} = \frac{r(p_{t}, q_{0})}{\sum_{i = 1}^{n} p_{i0} y_{i0}} \geq \frac{\sum_{i = 1}^{n} p_{it} y_{i0}}{\sum_{i = 1}^{n} p_{i0} y_{i0}};
\end{align*}
a Laspeyres index understates an increase in price over time because it does not take into account the substitution of outputs over time that is part of the output-price index. This is the opposite direction of substitution bias for an input-price index, and means that the direction of substitution bias depends on what the price index is trying to measure.

## Cost-of-living index

A cost-of-living index is entirely analogous to an input-price index, except that it measures the cost to a representative consumer associated with achieving a fixed level of utility from consumption---how does a consumer's expenditure change from a change in price to keep them as well off as they were in period 0? The theory is exactly the same as an input-price index, except that outputs $y_0$ are replaced with a measure of utility from consumption in period 0 in the expenditure function. That is, a cost of living index is
\begin{align*}
I^{C} = \frac{e(p_{t}, u_{0})}{e(p_{0}, u_{0})},
\end{align*}
where $u_{0}$ is the consumer's utility from consumption in period 0. Other than a change in interpretation, the mechanics of a cost-of-living index are identical to an input-price index, and will not be repeated.

## Approximating an economic index

An economic price index cannot be directly calculated in practice. There is no hope of calculating either an input-price or output-price index without knowledge of the firm’s technology of production, because the form of the firms' expenditure or revenue function is unknown. The problem is even more severe for a cost-of-living index, as it requires knowledge of consumer preferences to construct the consumer's expenditure function. The best that can be done is to approximate an economic index using data on observable prices and quantities. Both the arithmetic Laspeyres and geometric Laspeyres indices offer a good approximation to either the input price, output-price index, or cost-of-living index, at least to a first-order approximation.

The argument for approximating an economic index with an arithmetic Laspeyres or geometric Laspeyres is the same for an input-price index, an output-price index, and a cost-of-living index, and so attention is restricted to approximating an input-price index. To show that the Laspeyres index approximates the input-price index, recall that
\begin{align*}
e(p_{0}, y_{0}) = \sum_{i = 1}^{n} p_{i0} q_{i0}.
\end{align*}
Now, it can be shown that the best linear approximation to the expenditure function with period $t$ prices is
\begin{align*}
e(p_{t}, y_{0}) \approx \sum_{i = 1}^{n} p_{it}q_{i0}
\end{align*}
whenever period-$t$ prices are not too different from period-0 prices.^[This follows from Shephard's lemma [@mcfadden1978], which implies that $e(p_{t}, y_{0}) = \sum_{i = 1}^{n} p_{it}q_{i0} + \eta(p_{t} - p_{0})||p_{t} - p_{0}||$, where $\eta(p_{t} - p_{0}) \rightarrow 0$ when $p_{t} \rightarrow p_{0}$.] Therefore
\begin{align*}
\frac{e(p_{t}, y_{0})}{e(p_{0}, y_{0})} \approx \frac{\sum_{i = 1}^{n} p_{it} q_{i0}}{\sum_{i = 1}^{n} p_{i0} q_{i0}},
\end{align*}
at least for small price changes. 

Similarly, for the geometric Laspeyres, the best linear approximation is based on
\begin{align*}
\log(e(p_{t}, y_{0})) - \log(e(p_{0}, y_{0})) \approx \sum_{i = 1}^{n} \frac{p_{i0} q_{i0}}{\sum_{j = 1}^{n} p_{j0} q_{j0}} \log\left(\frac{p_{it}}{p_{i0}} \right).
\end{align*}
Therefore
\begin{align*}
I{^C} &= \exp(\log(e(p_{t}, y_{0})) - \log(e(p_{0}, y_{0}))) \\
&\approx \exp\left( \sum_{i = 1}^{n} \frac{p_{i0} q_{i0}}{\sum_{j = 1}^{n} p_{j0} q_{j0}} \log\left(\frac{p_{it}}{p_{i0}} \right) \right) \\
&= \prod_{i = 1}^{n} \left(\frac{p_{it}}{p_{i0}} \right)^{\omega_{i0}}
\end{align*}
where $\omega_{i0} = p_{i0} q_{i0} / \sum_{j = 1}^{n} p_{j0} q_{j0}$ is the period-0 expenditure weight for good $i$. As a geometric index is always smaller than its corresponding arithmetic index, and the Laspeyres index is too large relative to the input-price index (i.e., the approximation error is always positive due to substitution bias), the geometric Laspeyres index will give a better approximation to the input-price index than the Laspeyres index whenever the approximation error for the geometric index is positive.

In many cases the Fisher or Törnqvist index offers an even better approximation to an input-price index than the Laspeyres or geometric Laspeyres index. The argument for why these indices can be a better approximation are more complex---see @cpimanual[Chapter 17] and @ppimanual[Chapter 17] for details. The cost for this better approximation, however, is the need for more information about period $t$ quantities, which may or may not be available at the time when the index is actually calculated.^[In certain cases these approximations are exact. A Laspeyres index will be a true input-price index if the firm has a Leontief production function; a Fisher index will also be exact in this case. Similarly, a geometric Laspeyres will be a true input-price index if the firm has a Cobb-Douglas production functions; a Törnqvist index will also be exact in this case. The Lloyd-Moulton price index is an interesting case as it is exact whenever the firm has a constant elasticity of substitution production function, but it only requires period-0 quantity information.]

# The stochastic approach

The axiomatic and economic approaches to motivating a price index take prices as fixed. As the name suggests, the stochastic approach does not; instead, prices are treated as random, at least from the point of view of whoever is compiling the price index. This is not to say that prices are chosen or determined at random, but simply that there is a distribution of prices for goods and services transacted, and observing any given price is akin to a random draw from this distribution. The obvious benefit of this approach is that it agrees with the usual practice of calculating a price index using a sample of data, allowing for an explicit treatment of the statistical properties of a price index.^[Formally, in the stochastic approach, goods and services are modeled as belonging to a probability space $(\Omega, \mathcal{F}, P)$, where $\Omega$ is the (finite) set of goods and services that are transacted, $\mathcal{F}$ is the power set of $\Omega$, and $P$ is a probability measure that gives the likelihood of observing a good or service in $\Omega$ transacted. There is then a mapping from $\Omega$ to $\mathbb{R}_{+}^{2}$ that gives the price of a good in period 0 and period $t$.] 

At a conceptual level, however, the stochastic approach motivates a price index by one of its main uses: deflating and inflating prices across time. The act of deflating/inflating prices is essentially one of prediction---what would the price of a good or service be in another period?---and a price index can be motivated by examining how to pick a single value that bests predicts a change in price for a population of goods sold between two periods.

This section of the course concludes the journey into price index theory by giving a somewhat more thorough introduction to the stochastic approach than is seen elsewhere. This is because the stochastic approach is probably the most practical of the three approaches. While not as lofty as the axiomatic or economic approaches, it offers the most useful model for actually producing a price index as a macroeconomic statistic.

&#128214; PPI Manual: Chapter 1, section D; Chapter 16, section D.

## The optimal prediction problem

The starting point for the stochastic approach is a distribution of $n$ price relatives between period 0 and period $t$, with the price relative for good $i$ given by $p_{it} / p_{i0}$, for the population (universe) of all $n$ goods and services to be measured by the price index. Associated with each good $i$ is the probability $P_{i}$ of observing this good transacted over both periods in the population of goods measured by the index, and this in turn gives a measure of frequency for observing different values for changes in price over time. Put differently, a price relative $p_{t} / p_{0}$ is treated as a random variable in the stochastic approach, the distribution of which depends on the underlying distribution of goods and services that form the scope of the price index.^[There is a tendency to think of this distribution as being Gaussian, but doing so means that some goods and services have negative prices. In most cases price relatives cannot be distributed Gaussian.]

Given a distribution of price relatives, the best predictor of a change in price between period 0 and period $t$ is the value $I^{A}$ that minimizes the expected prediction error. Formally, the best predictor solves the following problem^[This is a prediction problem using a quadratic loss function, to ensure that the prediction error is always positive, and to formalize the idea that a large misprediction is more costly than many small mispredictions. Different loss functions usually give different optimal predictors; for example, the absolute loss function returns the median as the best predictor, which finds applications for housing price indices. If price relatives are symmetrically distributed, then all symmetric, convex loss functions give the same price index [@lehmann1998, Chapter 1 Corollary 7.19].]
\begin{align*}
\min_{I} E\left[\left(\frac{p_{t}}{p_{0}} - I \right)^{2}\right],
\end{align*}
where $E$ is the expected value operator, taken over the distribution of price relative. As is well known, the solution to this problem is to set $I^{A} = E(p_{t} / p_{0})$ [@lehmann1998, Chapter 1 Example 7.17]; that is, the best predictor of a change in price between two periods is the expected change in price. While it may seem unusual to express a price index in terms of an expected value, this simply emphasizes that a price index is rightfully a feature of the distribution of prices in the population. This is a key feature of the stochastic approach, and is what allows for a meaningful analysis of the statistical properties of a price index when calculated with a sample of price data from the population.

The figure gives an example of what the prediction problem looks like. Given a distribution of price relatives (solid line), there is an associated expected prediction error with each value that a price index can take (dashed line). The best choice for a price index as a predictive tool is the value that minimizes the expected prediction error (dotted line).

```{r, echo=FALSE}
library(ggplot2)
set.seed(12345)
d <- rlnorm(100, 0.25, 0.25)
x <- seq(0, 3, length.out = length(d))
y <- sapply(x, function(z) mean((d - z)^2))

ggplot() +
  geom_density(aes(d)) +
  geom_line(aes(x, y / 2), linetype = "dashed") +
  geom_vline(xintercept = mean(d), linetype = "dotted") +
  theme_classic() +
  labs(x = "Price relative/Index value", title = "Example of the prediction error associated with different index values") +
  scale_y_continuous("Density", sec.axis = sec_axis(~ . * 2, name = "Expected prediction error"))
```

As the expected value is just a weighted average, the index $I^{A} = E(p_{t} / p_{0})$ is simply an arithmetic index that averages price relatives. What’s interesting is that the weights now have a new interpretation---they are the probability of observing a good or service transacted in the population. That is,
\begin{align*}
I^{A} = \sum_{i = 1}^{n} \frac{p_{it}}{p_{i0}} P_{i}.
\end{align*}
Different arithmetic price-index formulas---e.g., Laspeyres, Paasche, Lowe---thus correspond to different statements about what determines the probability of observing a transaction. For example, with a Laspeyres index the probabilities are given by period-0 expenditure or revenue shares. This amounts to a statement that the probability of observing a transaction for a good is the likelihood of spending or receiving a dollar on that good in period 0.

## Geometric price indices as a best predictor

A geometric index can be motivated in the same way as an arithmetic index. Formally, a geometric index is the value $I^{G}$ that solves
\begin{align*}
\min_{I} E\left[\left(\log\left(\frac{p_{t}}{p_{0}}\right) - \log(I) \right)^{2}\right],
\end{align*}
the solution to which is $I^{G} = \exp(E[\log(p_{t} / p_{0})])$. But this is just a geometric index, as
\begin{align*}
\exp\left(E\left[\log\left(\frac{p_{t}}{p_{0}}\right)\right]\right) &= \exp\left(\sum_{i = 1}^{n} P_{i} \log\left(\frac{p_{it}}{p_{i0}}\right)\right) \\
&= \prod_{i = 1}^{n} \left(\frac{p_{it}}{p_{i0}}\right)^{P_{i}},
\end{align*}
with weights equal to the probability of observing a price relative. It is worth noting that, due to the logarithms in the prediction problem, a geometric index can equally be motivated as finding a value $I^{G}$ such that $I^{G} \times p_{i0}$ best predicts $p_{it}$ (or $p_{it} / I^{G}$ best predicts $p_{i0}$). This is a property not shared with arithmetic indices. Whereas an arithmetic index predicts price changes over time, a geometric index takes the price for a good in period 0, inflates/deflates it with the price index, and uses the result to predict the price for that good in period $t$. Consequently, a geometric index fits more neatly into the stochastic approach as it directly corresponds with how a price index is used to inflate and deflate prices over time in practice.^[Motivating a price index as solving the problem $\min_{I} E[(p_{t} - p_{0} I)^{2}]$ results in $I = E(p_{t} p_{0}) / E(p_{0}^{2})$, which is a rather unusual price index.] 

The Törnqvist index usually comes out as the best index in the stochastic approach because it picks a sensible value to represent the probability of observing a price relative. The idea behind the Törnqvist probabilities is that the likelihood of observing a particular price relative for a good depends on the expenditure/revenue share of that good across both periods. Thus, the Törnqvist index sets the probabilities as average expenditure shares:
\begin{align*}
P_{i} = \frac{1}{2} \frac{p_{i0}q_{i0}}{\sum_{j = 1}^{n} p_{j0}q_{j0}} + \frac{1}{2} \frac{p_{it}q_{it}}{\sum_{j = 1}^{n} p_{jt}q_{jt}}.
\end{align*}
The disadvantage of these probabilities is that they require information for both period-0 and period-$t$ expenditure/revenue shares, something that may not be known at the time the index is calculated.

## More general price indices

The arithmetic and geometric indices are special cases of a broader class of price indices that solve the following prediction problem:
\begin{align*}
\min_{I} E\left[\left(\left(\frac{p_{t}}{p_{0}}\right)^{r} - I^{r} \right)^{2}\right],
\end{align*}
for some $r \neq 0$. The solution to this problem is $I = E((p_{t} / p_{0})^{r})^{1 / r}$. Setting $r = 1$ gives an arithmetic index, whereas taking $r \rightarrow 0$ gives a geometric index [@bullen2003, III 1 Theorem 2].

What's useful about this approach is that many other types of price indices correspond to different choices of $r$, and these in turn can be motivated as solving a type of prediction problem. Setting $r = -1$, for example, yields a harmonic price index
\begin{align*}
I^{H} = \left(\sum_{i = 1}^{n} \frac{P_{i}}{p_{it} / p_{i0}} \right)^{-1}.
\end{align*}
When the probability of observing a good is given by its period-$t$ expenditure share, then this is the Paasche index. Setting $r = 1 - \sigma$, where $\sigma$ is the elasticity of substitution, results in the Lloyd-Moulton price index
\begin{align*}
I^{LM} = \left(\sum_{i = 1}^{n} P_{i} \left(\frac{p_{it}}{p_{i0}}\right)^{1 - \sigma}\right)^{1 / (1 - \sigma)}
\end{align*}
when the probabilities are period-0 expenditure/revenue shares.

An interesting point about these more general types of price indices is that, for a given set of weights, the index value is larger when the parameter $r$ increases [@bullen2003, III 3.1 Theorem 1]. This gives the familiar result that an arithmetic index is larger than a geometric index, which in turn is larger than a harmonic index, but it can also be used to rank more exotic types of indices like the Lloyd-Moulton index.

## Statistical inference

In practice the entire distribution of price relatives is usually not known, and an index is calculated using a sample of prices collected from producers or retailers. This means that the index values are calculated with an estimator for either $I^{A}$ or $I^{G}$, depending on whether an arithmetic or geometric index is the target index. Although the topics of sampling and statistical inference get complicated fast, and are beyond the scope of this course, it is worth examining how the arithmetic and geometric indices behave when calculated with a random sample of price data.^[See [@balk2008, Chapter 5] for an introduction to sampling and statistical inference for price indices.] One of the benefits of the stochastic approach is that it gives insight into the problem of estimating a price index with a sample.

With random sampling, a natural approach for estimating the arithmetic index is to replace the expected value---a population average---with the sample average. This gives a method-of-moments estimator $\hat{I}^A = 1 / n_{s} \sum_{i = 1}^{n_{s}} p_{it} / p_{i0}$, where $n_{s}$ is the sample size, which is just a Carli index. If price relatives are sampled at random, then is it easy to see that $E(\hat{I}^{A}) = I^{A}$, so the Carli index is an unbiased estimator for the arithmetic index.

A natural estimator for the geometric index is $\hat{I}^{G} = \prod_{i = 1}^{n_{s}} (p_{it} / p_{i0})^{1 / n_{s}}$, the Jevons index. Unlike the Carli index, however, the Jevons index is a biased estimator of the geometric index. It is again straightforward to show that $E(\hat{I}^{G}) \geq I^{G}$, with $E(\hat{I}^{G}) = I^{G}$ only holding in very special circumstances---the Jevons index systematically overestimates the geometric index (i.e., it is biased upwards).^[The Jevons index is not biased in cases where the sampling distribution is degenerate, or the variance in price relatives is zero. See [@lehmann1998, Chapter 1 Theorem 7.5].] Although biasedness is a disadvantage of the Jevons index, the bias is not the only important statistical property of an estimator, and the Jevons index has other desirable statistical properties (e.g., it is a consistent estimator of the geometric index, and in certain circumstances achieves the maximum likelihood efficiency bound).^[The Carli index is also a consistent estimator of the arithmetic index under random sampling, but it cannot be a maximum likelihood estimator as this would require price relatives to have a Gaussian distribution, which means that price relatives can be negative. By contrast, the Jevons index is a maximum likelihood estimator for the geometric index if price relatives have a log-normal distribution, which implies that prices are always positive.] It is possible to adjust for the upwards bias in the Jevons by dividing the Jevons index by $1 + \sigma^{2}/(2n)$, where $\sigma^{2}$ is the variance of the log price relatives [@kennedy2003, p. 41], but this is not usually done in practice.

# Assignment 2

Answers for these questions come from both the course content and the readings. Each question is worth one point, for a total of 20 points. Passing this module requires at least 65% (13 out of 20 correct). Email your answers to one of the course instructors (either [Steve Martin](mailto:steve.martin5@canada.ca) or [Rebecca Meier](mailto:rebecca.meier@canada.ca)) when you are finished.

**Question 1** True or false: The Laspeyres index is a cost-of-living index if consumers do not substitute away from more expensive goods when prices change.

**Question 2** True or false: The time-reversal test says that a price index between period 0 and period 1 is the same as the reciprocal of the price index between period 1 and period 0.

**Question 3** What is the difference between the economic and axiomatic approaches to index numbers?

a) Prices and quantities are independent in the axiomatic approach and dependent in the economic approach.

b) The economic approach treats prices as fixed, whereas the axiomatic approach treats prices as random.

c) The economic approach consists of a series of test based on economic theory to gauge the appropriateness of an index number, while the axiomatic approach uses the fundamental axioms from set theory to gauge how well an index number compares lists of prices.

d) The axiomatic approach and the economic approach are equivalent.

e) None of the above.

**Question 4** What weights does the Palgrave index use to aggregate price relatives between period 0 and period 1?

a) Period-0 expenditure/revenue shares.

b) Period-1 expenditure/revenue shares.

c) The geometric average of period-0 and period-1 expenditure/revenue shares.

d) The harmonic average of period-0 and period-1 expenditure/revenue shares.

e) None of the above.

**Question 5** True or false: The Fisher index is highly regarded as an index number because it satisfies the most important axioms and always corresponds to a cost-of-living index.

**Question 6** True or false: The time-reversal test says that a price index and a quantity index have the same functional form.

**Question 7** Which axiom does the Dutot index not satisfy?

a) Monotonicity.

b) Continuity.

c) Dimensional invariance.

d) Circularity.

e) None of the above.

**Question 8** True or false: It is impossible for a geometric Laspeyres index to be a cost-of-living index.

**Question 9** What type of index should be used to calculate a Laspeyres quantity index by deflating the change in aggregate value between two periods?

a) Palgrave index.

b) Laspeyres index.

c) Paasche index.

d) Fisher index.

e) Geometric Laspeyres index.

**Question 10** True or false: The Jevons index is a biased estimator of the geometric index in the population under random sampling.

The next 4 questions use data in the following table that contains a population of three price relatives, each with equal probability, and all possible samples from this population.

| Population of price relatives | Sample 1 | Sample 2 | Sample 3 |
| ---                           | ---      | ---      | ---      |
| 1.2                           | 1.2      | 1.2      | 1.1      |
| 1.1                           | 1.1      | 1.35     | 1.35     |
| 1.35                          | ...      | ...      | ...      |

**Question 11** What is the value of the geometric index in the population?

a) 121.2

b) 100

c) 120.5

d) 129.8

e) 98.7

**Question 12** What is the (arithmetic) average value of the Jevons indices in each sample?

a) 121.2

b) 119.4

c) 121.3

d) 100

e) 123.1

**Question 13** What is the value of the bias in the Jevons index?

a) 0

b) -0.2

c) 0.1

d) 0.8

e) -1.3

**Question 14** What is the value of the bias in the Carli index?

a) 1.1

b) -0.4

c) -0.2

d) 0.7

e) 0


**Question 15** True or false: If a representative consumer has a constant elasticity of substitution utility function, the magnitude of the substitution bias increases as the elasticity of substitution increases.

The next four questions use data in the following table that contains information on prices and quantities for two inputs over two periods, along with a true input-price index.

| Period | Price 1 | Price 2 | Quantity 1 | Quantity 2 | Input-price index |
| ---    | ---     | ---     | ---        | ---        | ---               |
| 0      | 100     | 60      | 141        | 391        | 100.0             |
| 1      | 120     | 80      | 160        | 360        | 128.0             |

**Question 16** What is the value of the Laspeyres index?

a) 101.0

b) 133.3

c) 128.0

d) 128.3

e) 99.3

**Question 17** What is the value of the Paasche index?

a) 127.7

b) 131.2

c) 101.0

d) 99.1

e) 130.0

**Question 18** What is the value of the Jevons index?

a) 120.1

b) 128.2

c) 99.0

d) 126.5

e) 98.4

**Question 19** True or false: The Jevons index calculated in question 18 is closer in value to the input-price index than the Fisher index.

**Question 20** True or false: It is possible to construct an input-price index for a firm that has market power for the goods it sells.
